# Generated by Django 5.2 on 2025-04-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_city_weatherdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='weathersearch',
            old_name='searched_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='city',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-11 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='icon',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='weather_api.city'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='weathersearch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='weather_api.city'),
        ),
    ]
